# Generated by Django 5.1.6 on 2025-03-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finger_print', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='client_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
